def test_call_fails(log_screenshot_with_trace):
    assert 0
